services:
  invisterra-app:
    image: invisterra-app:latest
    build:
      context: https://github.com/vGiacomov/INVISTERRA.git
      dockerfile: Dockerfile

    container_name: invisterra-app
    ports:
      - "8501:8501"
    restart: unless-stopped
    environment:
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
      - STREAMLIT_SERVER_HEADLESS=true
      - STREAMLIT_BROWSER_GATHER_USAGE_STATS=false
    volumes:
      - ./data:/app/data
      - ./uploads:/app/uploads
    networks:
      - invisterra-network

networks:
  invisterra-network:
    driver: bridge
